---
# Input/Intake Topics
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-intake
  title: Intake Topic
  description: Entry point for all incoming customer messages before moderation
  tags:
    - kafka
    - topic
    - message-intake
    - entry-point
spec:
  type: topic
  owner: platform-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-message
  title: Message Topic
  description: Contains messages for customer data processing and structured output analysis
  tags:
    - kafka
    - topic
    - message-processing
spec:
  type: topic
  owner: platform-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-router
  title: Router Topic
  description: Messages routed for AI classification and routing decisions
  tags:
    - kafka
    - topic
    - ai-routing
spec:
  type: topic
  owner: platform-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-documents
  title: Documents Topic
  description: Document content for embedding generation and vector storage
  tags:
    - kafka
    - topic
    - documents
    - embeddings
spec:
  type: topic
  owner: ai-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
# Routing Output Topics (Router-AI produces)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-support
  title: Support Topic
  description: Support-related messages routed by AI classifier to support team
  tags:
    - kafka
    - topic
    - support
    - ai-routing
spec:
  type: topic
  owner: support-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-finance
  title: Finance Topic
  description: Finance-related messages routed by AI classifier to finance team
  tags:
    - kafka
    - topic
    - finance
    - ai-routing
spec:
  type: topic
  owner: finance-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-website
  title: Website Topic
  description: Website-related messages routed by AI classifier to website team
  tags:
    - kafka
    - topic
    - website
    - ai-routing
spec:
  type: topic
  owner: website-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-unknown
  title: Unknown Topic
  description: Messages that cannot be classified by AI router - requires manual review
  tags:
    - kafka
    - topic
    - unclassified
    - manual-review
spec:
  type: topic
  owner: platform-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
# Processing Output Topics
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-outflow
  title: Outflow Topic
  description: Processed responses from AI assistants and moderated content flowing out of the system
  tags:
    - kafka
    - topic
    - ai-responses
    - output
spec:
  type: topic
  owner: platform-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-structured-output
  title: Structured Output Topic
  description: Structured information extracted from unstructured messages by AI
  tags:
    - kafka
    - topic
    - structured-data
    - ai-extraction
spec:
  type: topic
  owner: ai-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-customer-data
  title: Customer Data Topic
  description: Customer data events and updates from customer data service
  tags:
    - kafka
    - topic
    - customer-data
    - events
spec:
  type: topic
  owner: customer-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
---
# Error Handling Topic
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-topic-error
  title: Error Topic
  description: Error events from all services for centralized error handling and monitoring
  tags:
    - kafka
    - topic
    - error-handling
    - monitoring
spec:
  type: topic
  owner: platform-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker 