apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: document-embedding
  title: Document Embedding Service
  description: Service for generating and storing document embeddings using LangChain4j and Milvus vector database. Processes documents from Kafka and stores embeddings for similarity search.
  tags:
    - java
    - quarkus
    - kafka
    - milvus
    - langchain4j
    - embeddings
    - ai
  annotations:
    backstage.io/source-location: url:https://github.com/summit2025-ai-demo/document-embedding
    quarkus.io/profile: jvm
spec:
  type: service
  lifecycle: production
  owner: ai-team
  system: ai-customer-service-platform
  dependsOn:
    - resource:kafka-message-broker
    - resource:milvus-vector-database
    - resource:openai-service
  providesApis: []
  consumesApis: [] 